### ISSUE TITLE
Getting internal server error when log in through Facebook

### ISSUE THREAD

**Issue by theoziran** [arius86/squad-health-check#1]
As you can see when I tried to authenticate using my Facebook account it just shows internal server error. 
<img width="255" alt="screen shot 2017-07-12 at 11 52 46" src="https://user-images.githubusercontent.com/331873/28112274-ad98f986-66f8-11e7-88f3-6c9f31a49cec.png">

**Comment by arius86** [comment]
Solved in last update, thanks @theoziran
