### ISSUE TITLE
squadhealthcheck.info is not functional

### ISSUE THREAD

**Issue by mikeger** [arius86/squad-health-check#13]
Hey, I've used your tool in the past and I really like it. However right now it looks like some BE piece of it is down, so when I open https://squadhealthcheck.info and try to start the new squad check nothing happens (Chrome, Safari). 

I see some JS errors in the JS console, but it looks easy to reproduce.

**Comment by arius86** [comment]
Solved, thanks for noticing.

**Comment by mikeger** [comment]
💯 , works now, thanks @arius86 !
