### ISSUE TITLE
Site Isn't Loading

### ISSUE THREAD

**Issue by RashaHussein** [arius86/squad-health-check#15]
I am unable to view my quiz via the direct link or log in to my account to see the answers. 
<img width="1784" alt="Screen Shot 2021-12-14 at 11 09 47 AM" src="https://user-images.githubusercontent.com/3938069/146055488-3234ce8a-f302-4ffd-9b73-16d623f804f7.png">

**Comment by arius86** [comment]
Thanks for reporting!
