### ISSUE TITLE
link copy issue under firefox

### ISSUE THREAD

**Issue by bbonnesoeur** [arius86/squad-health-check#3]
Hello,

thanks for this great tool !

just to mention a minor bug, but when you finish the creation of a squad health check on the page where the mention "Open following link or scan qrcode to join:" is displayed, you can't select the healthchek URL to copy / past it.

it works great under Chromium browser.

I'm under Firefox 63 64 bits / Ubuntu 16.04

**Comment by arius86** [comment]
It was fixed with https://github.com/arius86/squad-health-check/pull/5 
Thanks for the contribution!
