### ISSUE TITLE
Overall state icon doeos not work after update

### ISSUE THREAD

**Issue by arius86** [arius86/squad-health-check#7]
After the metoer update overall icons stoped working, due to the changes in underlying packages. MongoDB aggregate function is the issue:

<img width="586" alt="Screen Shot 2019-12-04 at 08 36 53" src="https://user-images.githubusercontent.com/1889755/70122611-400e0e80-1671-11ea-894c-ef13d3e31119.png">

**Comment by naphox** [comment]
Hey Arius, any idea of when this will be solved? Thanks alot for the tool!

**Comment by PhKP** [comment]
Thank you very much for making this awesome tool! I am also missing the overall state..

**Comment by arius86** [comment]
Overall state icons has been fixed in the latest update, happy new year!

**Comment by PhKP** [comment]
Thanks! :D
